### ISSUE TITLE
parsing of string does not succeed

### ISSUE THREAD

**Issue by al-niessner** [NASA-PDS/api-search-query-lexer#1]
**Describe the bug**
Given the simple URL from [pds-api 54](https://github.com/NASA-PDS/pds-api/issues/54) `/products?q="lid eq *text*"` and expectation (acceptance criteria), the registry-api-service when nuts and blew up with out of memory. Tracked it down to this module. Turns out there is a simple infinite loop in [ANTLR](https://www.antlr.org/index.html) 4.9.2 and earlier that is most likely a fault of the language or how it is being parsed because the [ANTL FAQ](https://github.com/antlr/antlr4/blob/4.9.2/doc/faq/getting-started.md) suggests that not terminating the stream is the biggest problem and the infinite loop is caused by never finding the end of the stream even though all data has been read.

**To Reproduce**
Run/Debug in Eclipse `api.pds.nasa.gov.api_search_query_lexer.TestParsing`.

**Expected behavior**
TestParsing should run to completion and successfully parse the `lid eq *text*` string without running out of memory.

**Version of Software Used**
ANTLR 4.3, 4.7, 4.9.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner 

I came back to the specification of the API as written originally by the working group and actually that would be good if you can manage string without '"' (double quotes): see https://docs.google.com/document/d/16d0MVh48bFLvWsa5-B_Hy-cby1rGWdnNojWOJpUcOvA/edit#heading=h.3pbz9ppxrxvr

Just to make sure, I checked that we actually manage differently numbers and string in the API (ie in the elasticsearch query) and yes we do, so we need to keep to cases for string and numbers in the grammar (see /pds-api-service/src/main/java/gov/nasa/pds/api/engineering/elasticsearch/Antlr4SearchListener.java, line 197).

Thanks,

Thomas
